# Generated by Django 2.2.5 on 2019-12-30 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_followlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followlog',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', related_query_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
