# Generated by Django 2.2.5 on 2019-12-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191230_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='followlog',
            name='blocked_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='followlog',
            name='unfollowed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
