# Generated by Django 2.2.5 on 2020-02-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='showcase',
            new_name='post',
        ),
    ]
