# Generated by Django 2.2.5 on 2019-11-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='user',
        ),
    ]
